### PR TITLE
add long description to setup.py from README.md

### PR DESCRIPTION
**Pull request by rcerven**
fixes https://github.com/DBuildService/dockerfile-parse/issues/72

Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by rcerven** [comment]
import added

**Comment by MartinBasti** [comment]
Drop `encoding=` it is py3 only or use `io.open` instead

**Comment by twm** [comment]
@rcerven Did you mean to close this without merging? These changes appear to satisfy #72.

**Comment by rcerven** [comment]
@twm  yeah reopening will merge

**Pull request merged**
