### PR TITLE
Extend unicode testing

### PR DESCRIPTION
**Pull request by MartinBasti**
I extended string in current tests with '❤' character to test Unicode
non-ASCII characters (utf-8 encoded)

* OSBS-4457

Signed-off-by: Martin Bašti <mbasti@redhat.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
Instead of duplicating tests for unicode testing, I chose to update current tests with unicode character `❤`
Let me know what do you think

**Comment by MartinBasti** [comment]
I'm not sure about testing FROM instruction with unicode, because:
```
$ podman pull 'fedora:❤'                                                                         
Error: error pulling image "fedora:❤": unable to pull fedora:❤: error getting default registries to try: invalid reference format
```

**Comment by twaugh** [comment]
I don't see any spec that forbids UTF-8 in image tag names.

**Comment by MartinBasti** [comment]
I updated 2 simple cases to test `FROM` instruction

**Comment by MartinBasti** [comment]
no RN: only unitests updated

**Pull request merged**
